import com.sun.source.doctree.DocCommentTree;
import com.sun.source.doctree.DocTree;
import com.sun.source.doctree.TextTree;
import com.sun.source.doctree.LiteralTree;
import com.sun.source.doctree.LinkTree;
import com.sun.source.tree.ClassTree;
import com.sun.source.tree.CompilationUnitTree;
import com.sun.source.util.DocTrees;
import com.sun.source.util.JavacTask;
import com.sun.source.util.TreePath;
import javax.tools.ToolProvider;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.TreeMap;

/** Generates docs/PROJECT_MAP.md from top-level Java declarations and their first Javadoc sentence. */
public final class GenProjectMap {
    private record Entry(String name, String path, String description) {}

    public static void main(String[] args) throws Exception {
        Path root = Path.of(args.length == 0 ? "." : args[0]).toAbsolutePath().normalize();
        Path source = root.resolve("src/main/java");
        List<Path> files;
        try (var walk = Files.walk(source)) {
            files = walk.filter(p -> p.toString().endsWith(".java")).sorted().toList();
        }
        var compiler = ToolProvider.getSystemJavaCompiler();
        if (compiler == null) throw new IllegalStateException("Run with a JDK, not a JRE");
        var packages = new TreeMap<String, List<Entry>>();
        try (var manager = compiler.getStandardFileManager(null, null, StandardCharsets.UTF_8)) {
            var task = (JavacTask) compiler.getTask(null, manager, null, List.of("-proc:none"), null,
                    manager.getJavaFileObjectsFromPaths(files));
            var docs = DocTrees.instance(task);
            for (CompilationUnitTree unit : task.parse()) {
                String packageName = unit.getPackageName() == null ? "(default)" : unit.getPackageName().toString();
                for (var declaration : unit.getTypeDecls()) {
                    if (!(declaration instanceof ClassTree type)) continue;
                    DocCommentTree comment = docs.getDocCommentTree(TreePath.getPath(unit, type));
                    String description = comment == null ? "" : comment.getFirstSentence().stream()
                            .map(GenProjectMap::render).reduce("", String::concat);
                    description = description.replaceAll("\\{@(?:code|link|linkplain)\\s+([^}]+)}", "$1")
                            .replaceAll("<[^>]+>", "").replaceAll("\\s+", " ").trim().replace("|", "\\|");
                    if (description.isEmpty()) description = "Javadoc summary not yet supplied.";
                    String path = root.relativize(Path.of(unit.getSourceFile().toUri())).toString().replace('\\', '/');
                    packages.computeIfAbsent(packageName, k -> new ArrayList<>())
                            .add(new Entry(type.getSimpleName().toString(), path, description));
                }
            }
        }
        StringBuilder output = new StringBuilder("# Project map\n\n")
                .append("[![CI](https://github.com/ikanit1/mineclone/actions/workflows/ci.yml/badge.svg)](https://github.com/ikanit1/mineclone/actions/workflows/ci.yml)\n\n")
                .append("Generated by `java tools/GenProjectMap.java`. Edit source Javadoc, then regenerate; do not edit class rows manually.\n\n")
                .append("Start with [CLAUDE.md](../CLAUDE.md) for build commands and subsystem invariants. ")
                .append("`BuildInfo` is generated from `core/BuildInfo.java.template` by both build entry points.\n");
        int count = 0;
        for (var entry : packages.entrySet()) {
            output.append("\n## ").append(entry.getKey()).append("\n\n| Type | Purpose |\n|---|---|\n");
            entry.getValue().sort(Comparator.comparing(Entry::name));
            for (Entry row : entry.getValue()) {
                output.append("| [").append(row.name()).append("](../").append(row.path()).append(") | ")
                        .append(row.description()).append(" |\n");
                count++;
            }
        }
        output.append("\nTop-level declarations: ").append(count).append(".\n");
        Path destination = root.resolve("docs/PROJECT_MAP.md");
        Files.createDirectories(destination.getParent());
        Files.writeString(destination, output, StandardCharsets.UTF_8);
        System.out.println("PROJECT_MAP generated: " + count + " declarations, " + packages.size() + " packages");
    }

    private static String render(DocTree tree) {
        if (tree instanceof TextTree text) return text.getBody();
        if (tree instanceof LiteralTree literal) return literal.getBody().getBody();
        if (tree instanceof LinkTree link) return link.getLabel().isEmpty()
                ? link.getReference().getSignature()
                : link.getLabel().stream().map(GenProjectMap::render).reduce("", String::concat);
        return tree.toString();
    }
}
